version: '2'
services:
 qq:
   image: bestwu/qq:office    # 后面这个 office 改成 latest ， 登录的就是QQ，否则是Tim
   container_name: qq
   devices:
     - /dev/snd #声音
   volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - $HOME/TencentFiles:/TencentFiles
   environment:
     - DISPLAY=unix$DISPLAY
     - XMODIFIERS=@im=ibus #中文输入
     - QT_IM_MODULE=ibus
     - GTK_IM_MODULE=ibus
     - AUDIO_GID=29 # 可选 (29 parrotsec) 主机audio gid 解决声音设备访问权限问题
     - GID=1000 # 可选 默认1000 主机当前用户 gid 解决挂载目录访问权限问题
     - UID=1000 # 可选 默认1000 主机当前用户 uid 解决挂载目录访问权限问题
